name: hospital_management
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/praseth-002/project-dart-oop.git

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  uuid: ^4.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
